LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

ifdef WIFI_DRIVER_MODULE_PATH
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_PATH=\"$(WIFI_DRIVER_MODULE_PATH)\"
endif
ifdef WIFI_DRIVER_MODULE_ARG
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_ARG=\"$(WIFI_DRIVER_MODULE_ARG)\"
endif
ifdef WIFI_DRIVER_P2P_MODULE_ARG
LOCAL_CFLAGS += -DWIFI_DRIVER_P2P_MODULE_ARG=\"$(WIFI_DRIVER_P2P_MODULE_ARG)\"
endif
ifdef WIFI_DRIVER_MODULE_NAME
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_NAME=\"$(WIFI_DRIVER_MODULE_NAME)\"
endif

ifdef WIFI_SDIO_IF_DRIVER_MODULE_PATH
LOCAL_CFLAGS += -DWIFI_SDIO_IF_DRIVER_MODULE_PATH=\"$(WIFI_SDIO_IF_DRIVER_MODULE_PATH)\"
endif
ifdef WIFI_SDIO_IF_DRIVER_MODULE_ARG
LOCAL_CFLAGS += -DWIFI_SDIO_IF_DRIVER_MODULE_ARG=\"$(WIFI_SDIO_IF_DRIVER_MODULE_ARG)\"
endif
ifdef WIFI_SDIO_IF_DRIVER_MODULE_NAME
LOCAL_CFLAGS += -DWIFI_SDIO_IF_DRIVER_MODULE_NAME=\"$(WIFI_SDIO_IF_DRIVER_MODULE_NAME)\"
endif

ifdef BLUETOOTH_DRIVER_MODULE_PATH
LOCAL_CFLAGS += -DBLUETOOTH_DRIVER_MODULE_PATH=\"$(BLUETOOTH_DRIVER_MODULE_PATH)\"
endif
ifdef BLUETOOTH_DRIVER_MODULE_ARG
LOCAL_CFLAGS += -DBLUETOOTH_DRIVER_MODULE_ARG=\"$(BLUETOOTH_DRIVER_MODULE_ARG)\"
endif
ifdef BLUETOOTH_DRIVER_MODULE_NAME
LOCAL_CFLAGS += -DBLUETOOTH_DRIVER_MODULE_NAME=\"$(BLUETOOTH_DRIVER_MODULE_NAME)\"
endif



LOCAL_C_INCLUDES := \

LOCAL_SRC_FILES := \
        marvell_wireless_daemon.c


LOCAL_SHARED_LIBRARIES := \
    libc\
    libcutils \
    libutils \
    libnetutils

LOCAL_MODULE:=MarvellWirelessDaemon
LOCAL_MODULE_TAGS := optional


ifdef SD8787_NEED_CALIBRATE
LOCAL_CFLAGS += -DSD8787_NEED_CALIBRATE
endif

include $(BUILD_EXECUTABLE)


include $(CLEAR_VARS)
LOCAL_SRC_FILES:= \
	lib_marvell_wireless.c


LOCAL_SHARED_LIBRARIES := \
    libcutils \
    libutils 

LOCAL_MODULE_TAGS := optional
LOCAL_MODULE:= libMarvellWireless

include $(BUILD_SHARED_LIBRARY)



